version: '2.4'

services:

  frontend:
    image: "grocy/frontend:v3.3.2"
    container_name: grocy_frontend
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '0.0.0.0:8228:8080'
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grocy.rule=Host(`grocy.shaffer.network`)
      - traefik.http.routers.grocy.entrypoints=https
      - traefik.http.routers.grocy.tls=true
      - traefik.http.routers.grocy.middlewares=chain-oauth@file
      - traefik.http.routers.grocy.service=grocy
      - traefik.http.services.grocy.loadbalancer.server.port=8080

  backend:
    image: "grocy/backend:v3.3.2"
    container_name: grocy_backend
    build:
      args:
        GROCY_VERSION: v3.3.2
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /home/andrew/docker/grocy/db:/var/www/data
    env_file:
      - grocy.env
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
